server:
  port: 8080

spring:
  application:
    name: education-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${database.user:root}
    password: ${database.password:test123}
    url: ${database.url:jdbc:mysql://localhost:3306/education-service?createDatabaseIfNotExist=true}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        show_sql: true

jwt:
  signing-Key: va6w3Fr1goCcrues0p//L3fBWWYxG3u5DF4YKxXgEqtXGNjdMrbCVLRXhVd4b/tL